form-template-mvc/Models/ErrorViewModel.cs
using System;

namespace form_template_mvc.Models
{
    public class ErrorViewModel
    {
        public string RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

form-template-mvc/Models/FormData.cs
using System;
using System.Text.Json.Serialization;


namespace form_template_mvc.Models
{
    public class FormData
    {
        /// <summary>
        /// A unique ID that can be used for form input name attributes.
        /// </summary>
        [JsonPropertyName("form_id")]
        public string ID { get; set; }

        /// <summary>
        /// Question name is for used for form input labels
        /// </summary>
        [JsonPropertyName("question_name")]
        public string Name { get; set; }

        /// <summary>
        /// Default value to either apply to the form input or use if null value
        /// received from the form data.
        /// </summary>
        [JsonPropertyName("question_default_value")]
        public string DefaultValue { get; set; }

        /// <summary>
        /// Can be used as an alternative to ID as a unique identifier in
        /// a format thats nicer on the eyes
        /// </summary>
        [JsonPropertyName("code_name")]
        public string CodeName { get; set; }

        /// <summary>
        /// Tooltop message to display if set
        /// </summary>
        [JsonPropertyName("question_tooltip")]
        public string ToolTip { get; set; }

        /// <summary>
        /// Topic is the group of inputs a question belongs to.
        ///
        /// Such as property or applicant
        /// </summary>
        [JsonPropertyName("question_topic")]
        public string Topic { get; set; }

        /// <summary>
        /// Used to make decisions on input type to render for a field
        /// </summary>
        [JsonPropertyName("setting_formtype")]
        public string InputType { get; set; }

        /// <summary>
        /// The expected data type
        /// </summary>
        [JsonPropertyName("setting_datatype")]
        public string DataType { get; set; }

        /// <summary>
        /// String representation of the select dropdowns values.
        ///
        /// Note: Requires and intermediary step to be turned into a Dictionary
        /// to make it usable.
        /// </summary>
        [JsonPropertyName("setting_values")]
        public string SelectValues { get; set; }

        /// <summary>
        /// Is the input a required field. Used to set an inputs required attribute
        /// </summary>
        [JsonPropertyName("setting_required")]
        public bool IsRequired { get; set; }

        /// <summary>
        /// String representation of the validation rules to use.
        ///
        /// Split on pipe char in order to iterate on them
        /// </summary>
        [JsonPropertyName("setting_validation")]
        public string Validation { get; set; }
        
    }
}

form-template-mvc/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Logging;
using form_template_mvc.Models;
using form_template_mvc.Services;

namespace form_template_mvc.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;
        private readonly IFormFieldService _formsvc;

        public HomeController(ILogger<HomeController> logger, IFormFieldService formsvc)
        {
            _logger = logger;
            _formsvc = formsvc;
        }

        public async Task<IActionResult> Index()
        {
            var fields = await _formsvc.GetFormFieldsAsync();
            return View(fields);
        }

        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

form-template-mvc/ViewComponents/FormGroupViewComponent.cs
using form_template_mvc.Models;
using Microsoft.AspNetCore.Mvc;
using System.Collections.Generic;
using System.Threading.Tasks;
using System.Linq;
using form_template_mvc.Library.Form;

namespace form_template_mvc.ViewComponents
{
    [ViewComponent(Name = "FormGroup")]
    public class FormGroupViewComponent : ViewComponent
    {
        protected readonly IFormInputRepository _factory;

        public FormGroupViewComponent(IFormInputRepository factory)
        {
            _factory = factory;
        }

        /// <summary>
        /// Renders a group of inputs based on the given group/topic
        /// </summary>
        /// <param name="fields">List of all form data fields</param>
        /// <param name="group">What group/topic to filter on</param>
        /// <param name="title">Title of the rendered bootstrap card</param>
        public async Task<IViewComponentResult> InvokeAsync(IEnumerable<FormData> fields, string group, string title)
        {
            return await Task.Run(() => {
                List<InputModel> model = new();

                // If there was any ordering properties on the FormData we would sort then here.
                // For now just go with the order the api served up which is in db creation order.

                // Only used fields with the given group.
                foreach (FormData d in fields.ToList().Where(f => f.Topic == group))
                {
                    model.Add(_factory.CreateFormInput(d, group));
                }

                return View(new FormGroupModel()
                {
                    Title = title,
                    Data = model,
                });
            });
        }
    }

    public class FormGroupModel
    {
        public string Title { get; set; }
        public IEnumerable<InputModel> Data { get; set; }
    }
}

form-template-mvc/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

@model IEnumerable<form_template_mvc.Models.FormData>;


<div class="row">
    <div class="col-12 text-center">
        <h1 class="display-5">Form Field Template Example</h1>
    </div>
</div>
<form>
    @*
        Group inputs by a specific topic which in this case is applicants, but could be property/address etc
        and render the groups inputs in a dedicated container.

        For this example i'll just use a bootstrap card with a title.'
    *@
    <div class="col-6 offset-md-3 pt-5">
        @await Component.InvokeAsync("FormGroup", new { fields = Model, group = "applicant", title = "Applicant" })
    </div>
</form>

form-template-mvc/Views/Shared/Components/FormGroup/Default.cshtml
@using form_template_mvc.Library.Form;
@model form_template_mvc.ViewComponents.FormGroupModel;

<div class="card">
    <div class="card-header">
        <h5>@Model.Title</h5>
    </div>
    <div class="card-body">
        @foreach (var field in Model.Data)
        {
            switch (field.GetInputType())
            {
                case InputModel.InputType.TEXT:
                    <partial name="_TextInput" model="field" />
                    break;
                case InputModel.InputType.DATE:
                    <partial name="_DateInput" model="field" />
                    break;
                case InputModel.InputType.SELECT:
                    <partial name="_SelectInput" model="field" />
                    break;
                case InputModel.InputType.INVALID:
                default:
                    @*At least show something to say its broken*@
                    <p>Nope, that's not going to work. Use a valid input type!</p>
                    break;
            }
        }
    </div>
</div>

form-template-mvc/Views/Shared/_DateInput.cshtml
@using form_template_mvc.Library.Form;
@model InputModel;
@*
    this should be a DateInput type but the example admin form doesn't allow setting things like start,
    end dates for the input attrs. So just leaving as a TextInput cast for now.
*@
@{
    TextInput dateInput = (TextInput)Model;
}
<div class="form-group">
    <label for="@dateInput.GetID()">@dateInput.GetLabelText()</label>
    <input class="form-control" id="@dateInput.GetID()" type="date" name="@dateInput.GetNameAttribute()" @(dateInput.IsRequired() ? "required" : "") />
</div>

form-template-mvc/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - form_template_mvc</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">form_template_mvc</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2021 - form_template_mvc - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>

form-template-mvc/Views/Shared/_SelectInput.cshtml
@using form_template_mvc.Library.Form;
@model InputModel;
@{
    SelectInput selectInput = (SelectInput)Model;
}
<div class="form-group">
    <label for="@selectInput.GetID()">@selectInput.GetLabelText()</label>
    <select class="form-control" id="@selectInput.GetID()" name="@selectInput.GetNameAttribute()">
        @*Loop from the SelectInput options*@
        @foreach (var item in @selectInput.GetOptions())
        {
            <option value="@item.Key">@item.Value</option>
        }
    </select>
</div>

form-template-mvc/Views/Shared/_TextInput.cshtml
@using form_template_mvc.Library.Form;
@model InputModel;
@{
    TextInput textInput = (TextInput)Model;
}
<div class="form-group">
    <label for="@textInput.GetID()">@textInput.GetLabelText()</label>
    <input class="form-control" id="@textInput.GetID()" type="text" name="@textInput.GetNameAttribute()" @(textInput.IsRequired() ? "required" : "") />
</div>